param(
  [string]$Template,
  [string]$VersionFile
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot

if (-not $Template) { $Template = Join-Path $ProjectRoot "assets\templates\sie_template.pptx" }
if (-not $VersionFile) { $VersionFile = Join-Path $ProjectRoot "assets\templates\sie_template.version.txt" }
if (-not (Test-Path $Template)) { throw "Template not found: $Template" }

$hash = (Get-FileHash -Algorithm SHA256 -Path $Template).Hash.ToLower()
$now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$content = @(
  "template_file=$(Split-Path $Template -Leaf)"
  "sha256=$hash"
  "updated_at=$now"
  "note=Auto generated by update_template_version.ps1"
)

Set-Content -Path $VersionFile -Value $content -Encoding UTF8
Write-Host "[OK] Template version updated:"
Write-Host "file: $Template"
Write-Host "sha256: $hash"
Write-Host "version: $VersionFile"

