from .io import (
    build_deck_output_path,
    build_log_output_path,
    build_outline_output_path,
    build_ppt_output_path,
    default_deck_output_path,
    default_log_output_path,
    default_outline_output_path,
    default_ppt_output_path,
    load_deck_document,
    load_outline_document,
    write_deck_document,
    write_outline_document,
)
from .content_rewriter import RewriteAction, RewriteDeckResult, rewrite_deck, rewrite_slide, write_rewrite_log
from .ppt_engine import RenderArtifacts, generate_ppt
from .quality_checks import (
    AutoScoreResult,
    ContentWarning,
    QualityGateResult,
    calculate_auto_score,
    check_deck_content,
    check_slide_content,
    quality_gate,
    write_quality_gate_result,
)
from .schema import (
    DeckDocument,
    OutlineDocument,
    OutlineItem,
    SUPPORTED_LAYOUTS,
    SUPPORTED_THEMES,
    ThemeMeta,
    ValidatedDeck,
    collect_deck_warnings,
    normalize_deck_payload,
    validate_deck_payload,
)
from .services import (
    DeckGenerationRequest,
    OutlineGenerationRequest,
    V2MakeArtifacts,
    generate_deck_with_ai,
    generate_outline_with_ai,
    make_v2_ppt,
)
from .theme_loader import ThemeSpec, available_theme_names, load_theme

__all__ = [
    "DeckDocument",
    "DeckGenerationRequest",
    "OutlineDocument",
    "OutlineGenerationRequest",
    "OutlineItem",
    "RenderArtifacts",
    "RewriteAction",
    "RewriteDeckResult",
    "SUPPORTED_LAYOUTS",
    "SUPPORTED_THEMES",
    "ContentWarning",
    "AutoScoreResult",
    "QualityGateResult",
    "ThemeMeta",
    "ThemeSpec",
    "V2MakeArtifacts",
    "ValidatedDeck",
    "available_theme_names",
    "build_deck_output_path",
    "build_log_output_path",
    "build_outline_output_path",
    "build_ppt_output_path",
    "collect_deck_warnings",
    "check_deck_content",
    "check_slide_content",
    "calculate_auto_score",
    "default_deck_output_path",
    "default_log_output_path",
    "default_outline_output_path",
    "default_ppt_output_path",
    "generate_deck_with_ai",
    "generate_outline_with_ai",
    "generate_ppt",
    "load_deck_document",
    "load_outline_document",
    "load_theme",
    "make_v2_ppt",
    "normalize_deck_payload",
    "quality_gate",
    "rewrite_deck",
    "rewrite_slide",
    "validate_deck_payload",
    "write_deck_document",
    "write_outline_document",
    "write_quality_gate_result",
    "write_rewrite_log",
]
